### ISSUE TITLE
How to use with Behat.yml...?

### ISSUE THREAD

**Issue by BevanR** [minkphp/MinkZombieDriver#115]
How does one get Behat to use Zombie instead of Goutte or Selenium2?

I see the example usage code in the README.md, however I don't see how this can be used to configure Behat to use Zombie, and am not sure where to put it.  I tried `FeatureContext.php`, although I am pretty sure that is not right.

I also tried specifying `zombie` and `default_session` in `behat.yml` with no luck:

```yaml
default:
  extensions:
    Behat\MinkExtension\Extension:
      zombie: ~
      default_session: 'zombie'
```
