### ISSUE TITLE
Zombie return <html><head></head><body></body></html>

### ISSUE THREAD

**Issue by bourg-ismael** [minkphp/MinkZombieDriver#117]
Hi,

When I run my tests with zombie, my tests failed and return :

```
<html><head></head><body></body></html>
```

I tried without zombie and it work perfectly but when I use zombie I have this.

Here my behat.yml :

```
# behat.yml
default:
  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://192.168.33.120/
      javascript_session: zombie
      goutte:
        guzzle_parameters:
          curl.options:
            CURLOPT_HTTPHEADER: ["Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4;"]
      selenium2: ~
      zombie: ~
```
