### ISSUE TITLE
Not compatible with Zombie 4.x

### ISSUE THREAD

**Issue by jhedstrom** [minkphp/MinkZombieDriver#132]
When running against the latest Zombie, I am getting the following:

```
    Given I am on the homepage                         # Drupal\DrupalExtension\Context\MinkContext::iAmOnHomepage()
      Server process has been terminated: (8) [
      /usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:238
      var nonInheritedTags = new Set([
                                 ^
      ReferenceError: Set is not defined
          at Object.<anonymous> (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/html.js:238:28)
          at Module._compile (module.js:456:26)
          at Object.Module._extensions..js (module.js:474:10)
          at Module.load (module.js:356:32)
          at Function.Module._load (module.js:312:12)
          at Module.require (module.js:364:17)
          at require (module.js:380:17)
          at Object.<anonymous> (/usr/local/lib/node_modules/zombie/node_modules/jsdom/lib/jsdom/living/index.js:8:1)
          at Module._compile (module.js:456:26)
          at Object.Module._extensions..js (module.js:474:10)
          at Module.load (module.js:356:32)
          at Function.Module._load (module.js:312:12)
          at Module.require (module.js:364:17)
          at require (module.js:380:17)
          at Object.<anonymous> (/usr/local/lib/node_modules/zombie/lib/dom/index.js:5:11)
          at Module._compile (module.js:456:26)
      ] (RuntimeException)
    When I press on "Commits"
```

**Comment by MKorostoff** [comment]
I'm seeing this issue too

**Comment by aik099** [comment]
Please provide:

# example page html, that fails
# debug output of Behat, while it runs scenario that triggers the exception 

Most likely we'll end up with a bug in Zombie or JSDOM itself.

**Comment by jhedstrom** [comment]
Sure.

`composer.json`:

```json
{
    "require": {
        "behat/mink-zombie-driver": "^1.2",
        "behat/behat": "^3.0",
        "behat/mink-extension": "^2.0"
    }
}
```

`behat.yml`:
```yaml
default:
  suites:
    default:
      contexts:
        - Behat\MinkExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      zombie: ~
      base_url: http://www.wikipedia.org
      javascript_session: zombie
```

`features/test.feature`:
```cucumber
Feature: Illustrate Zombie JS behavior.

  @javascript
  Scenario: Visit Wikipedia
    Given I am on the homepage
```

**Comment by stof** [comment]
your issue with Set not being defined is an issue in your setup itself: Zombie 4 is not compatible with node.js 0.12 anymore. It requires running on io.js. So you would need to configure the driver to find io.js (or symlink it to make it available as ``node`` in your path):

```yaml
default:
  suites:
    default:
      contexts:
        - Behat\MinkExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      zombie:
        node_bin: iojs
      base_url: http://www.wikipedia.org
      javascript_session: zombie
```

Note however that we have not tested the driver on Zombie 4 yet (I thought about doing it but Travis does not provide io.js on PHP VMs, making it much more painful)
